### ISSUE TITLE
"No Secret specified"

### ISSUE THREAD

**Issue by sboesebeck** [loteoo/ks#2]
Hi,

this is a great idea, but unfortunately it does not work for me:

```
> ks add "mysecret" "test"
No secret specified. Please provide the value to encrypt
```

it will ask for the password though.

When trying to access elements in the keychain, it also does not work properly. I added an object called `testObject` to the `Secrets` keychain. When doing an ls, all looking good:

```
> ks ls
testObject
``` 

But accessing it does not work:

```
> ks show testObject
Secret "testObject" was not found in keychain.
```

**Comment by loteoo** [comment]
Hi @sboesebeck, thank you so much for creating this issue.

Silly me used a bash 5.0 feature in this is which meant for bash 3.2 (the bash version that is preinstalled on macs).

Would you please try running the install script again and let me know how it goes? Thank you so much once again.

cc: @brunoselvacj

**Comment by sboesebeck** [comment]
Thanks, now it works fine!
