### ISSUE TITLE
Docs/Readme how to for iCloud keychain

### ISSUE THREAD

**Issue by Moulick** [loteoo/ks#6]
Hi @loteoo, thank you for this tool. The readme mentions that 
> Optional backups, syncing and sharing with [iCloud Keychain](https://support.apple.com/en-ca/HT204085).

but I cannot figure out how to use `ks` to read a password from the iCloud Keychain. Can you please elaborate?

**Comment by henrik242** [comment]
ping @loteoo :)

**Comment by loteoo** [comment]
Hey @henrik242 , sorry for the late reply. Unfortunately it looks like iCloud keychains are stored in a different format that the security command cannot parse. You can see them in the `~/Library/Keychains` directory. The default one used by ks is the `Secrets` one. The iCloud one is also stored there under a directory with a long UUID. The Idea was that you would be able to do `ks -k iCloud ls` but that will not work, the format is different.

**Work around using iCloud drive:**

1. Move your keychain file to iCloud drive: 
```
mv "/Users/$USER/Library/Keychains/Secrets.keychain-db" "/Users/$USER/Library/Mobile Documents/com~apple~CloudDocs/Secrets.keychain-db"
```

2. Create a symlink from the for the Keychains directory to the keychain file: 
```
ln -s "/Users/$USER/Library/Mobile Documents/com~apple~CloudDocs/Secrets.keychain-db" "/Users/$USER/Library/Keychains/Secrets.keychain-db"
```

3. On your secondary computer, wait for the file to sync (or create a directory then delete it, that forces a refresh), then create a symlink. Same command as step 2.

Your keychains should now be synced & backed up in iCloud!

So anyways @Moulick, @henrik242 and @ivankovnatsky, my deepest apologies. I had made a wrong assumption. Hopefully the workaround is okay for you guys. I will update the readme soon.

**Comment by Moulick** [comment]
Thanks for the workaround @loteoo!
